### ISSUE TITLE
Please add UpdateKeys to manifest.json

### ISSUE THREAD

**Issue by Maikenvv** [jamescodesthings/smapi-better-sprinklers#1]
SMAPI can checks for updates when it boots up. Right now the following error appears:

> These mods have no update keys in their manifest. SMAPI may not notify you about updates for these mods. Consider notifying the mod authors about this problem.

This is a simple fix, by simply updating the UpdateKeys in `manifest.json`. Would you be willing to add this? I could fork the repo, but it seems overkill for a simple change.

`"UpdateKeys": [ "Nexus:17767", "GitHub:jamescodesthings/smapi-better-sprinklers" ]`

**Comment by jamescodesthings** [comment]
Thanks for the heads up, this has now been done on:

https://github.com/jamescodesthings/smapi-better-sprinklers/releases/tag/2.17.4
