### ISSUE TITLE
Error messaging when in UI

### ISSUE THREAD

**Issue by xenianth** [jamescodesthings/smapi-better-sprinklers#2]
Hey there! With the 1.6 update, I know a lot of things have broken. When you have the time, can you please look into this error from my SMAPI log?

Steps to reproduce:
- Hit K to display config UI
- Click any of the sprinkler type tabs on the left

Clicking any tab does nothing in-game; error message in SMAPI log every time a tab is clicked. The icons for sprinkler type in the UI are all the same Weed sprite.

```
14:58:47 | INFO | Better Sprinklers Plus | Running sprinklers
-- | -- | -- | --
14:58:47 | ERROR | Better Sprinklers Plus | This mod failed in the GameLoop.DayStarted event. Technical details:  Failed loading type 'StardewValley.Locations.BuildableGameLocation': TypeLoadException: Could not load type 'StardewValley.Locations.BuildableGameLocation' from assembly 'Stardew Valley, Version=1.6.0.24079, Culture=neutral, PublicKeyToken=null'.    at BetterSprinklersPlus.Framework.Helpers.LocationHelper.GetAllBuildableLocations()    at BetterSprinklersPlus.BetterSprinklersPlus.UnwaterAll() in /plugin/BetterSprinklersPlus/BetterSprinklersPlus.cs:line 265    at BetterSprinklersPlus.BetterSprinklersPlus.RunSprinklers() in /plugin/BetterSprinklersPlus/BetterSprinklersPlus.cs:line 182    at BetterSprinklersPlus.BetterSprinklersPlus.OnDayStarted(Object sender, DayStartedEventArgs e) in /plugin/BetterSprinklersPlus/BetterSprinklersPlus.cs:line 82    at StardewModdingAPI.Framework.Events.ManagedEvent`1.Raise(TEventArgs args) in SMAPI\Framework\Events\ManagedEvent.cs:line 101
```

Full log here: [https://smapi.io/log/4147b5db9fe04cbd8d8e55f64f92b285](https://smapi.io/log/4147b5db9fe04cbd8d8e55f64f92b285)

**Comment by Prattlemage** [comment]
Hi,

Just wanted to confirm this bug and let you know that I'm seeing the exact same issue.

Best Regards,
Prattle

**Comment by gingajamie** [comment]
Hey @jamescodesthings - I was experiencing the same as described in the couple of issues mentioned here. As well as the mod instantly crashing on Linux (Steam Deck).

I've been able to fix the issues and get the mod running locally for myself. Happy to push the changes to a branch and open a PR if you want to give me perms to do so on a temporary basis?

Cheers,
Jamie

**Comment by Prattlemage** [comment]
Hi @gingajamie, 

Until this is updated are you able to share your fix?

Thank you

**Comment by gingajamie** [comment]
You can find it here on my github - https://github.com/gingajamie/smapi-better-sprinklers-plus-encore/releases/tag/2.18.0

**Comment by gingajamie** [comment]
@Prattlemage - You can find a fixed version (2.18.0) on my github.

https://github.com/gingajamie/smapi-better-sprinklers-plus-encore/releases/tag/2.18.0

Let me know if any issues.

**Comment by jamescodesthings** [comment]
Hey, @gingajamie sorry for the delay getting back to you. I'm happy to merge PRs, or just make you a contributor so you can manage yourself.

If you chuck me a nexus user account I can give you access there too. Entirely up to you; but happy to make this an "anyone who wants to help can" kind of a situation.

**Comment by gingajamie** [comment]
Sounds good @jamescodesthings - Nexus account should just be the same username I have here, you should see one of the most recent comments on the Nexus mod from me too if that helps.

**Comment by jamescodesthings** [comment]
@gingajamie Nice one, I've added you to the Mod's permissions so you should now be able to edit/upload/etc. Feel free to upload your version, change stuff, do what you think feels right. I've split the DP reward to 50/50 to add you on too. Not sure if there's much huge benefit to Dontation Points but it doesn't feel right me taking the lot if you're putting effort in.

Also don't forget to add yourself to the credits.
