### ISSUE TITLE
Sprinklers not automatically watering increased area

### ISSUE THREAD

**Issue by FTOtter** [jamescodesthings/smapi-better-sprinklers#4]
Hello, 

Currently the sprinklers are only watering their default/vanilla tiles automatically each morning. They can be triggered manually and then they will water the modded tiles as well, but they don't do it on their own. 

Edit: Also unable to edit the tiles watered by anything other than the basic sprinkler.

**Comment by gingajamie** [comment]
You can find a fixed version (2.18.0) on my github.

https://github.com/gingajamie/smapi-better-sprinklers-plus-encore/releases/tag/2.18.0

Let me know if any issues.
